INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\base\models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\backend\settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /
INFO:django.utils.autoreload:D:\project\cookit\backend\backend\settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\food\models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\food\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\food\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\backend\urls.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\food\serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\backend\urls.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\project\cookit\backend\favorite_food\models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
INFO:django.utils.autoreload:D:\project\cookit\backend\favorite_food\serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'cookit.pagekite.me'. You may need to add 'cookit.pagekite.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'cookit.pagekite.me'. You may need to add 'cookit.pagekite.me' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'cookit.pagekite.me'. You may need to add 'cookit.pagekite.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'cookit.pagekite.me'. You may need to add 'cookit.pagekite.me' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /favicon.ico
INFO:django.utils.autoreload:D:\project\cookit\backend\backend\settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
WARNING:drf_yasg.inspectors.base:view's FavoriteFoodModelViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "D:\project\cookit\backend\base\views.py", line 45, in get_serializer
    return serializer_class(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: FavoriteFood() got unexpected keyword arguments: 'context'
